# Luau heuristic checker (originally generated by build_war_state.py 0.1.0).
# Strips comments/strings, checks bracket balance, block balance (function/if/do/repeat vs end/until),
# ModuleScript trailing return, and obvious non-Luau tokens. It is NOT a full Luau parser
# (see luau_parser.py for the stricter recursive-descent syntax check).

import re

_WORD = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def strip_luau(src):
    """Remove comments and string contents. Keeps newlines so line numbers stay valid."""
    out = []
    i, n = 0, len(src)
    while i < n:
        ch = src[i]
        if src.startswith("--", i):
            m = re.match(r"--\[(=*)\[", src[i:])
            if m:
                close = "]" + m.group(1) + "]"
                end = src.find(close, i + len(m.group(0)))
                if end == -1:
                    raise ValueError("unterminated block comment")
                out.append("\n" * src.count("\n", i, end))
                i = end + len(close)
                continue
            end = src.find("\n", i)
            if end == -1:
                break
            i = end
            continue
        m = re.match(r"\[(=*)\[", src[i:]) if ch == "[" else None
        if m:
            close = "]" + m.group(1) + "]"
            end = src.find(close, i + len(m.group(0)))
            if end == -1:
                raise ValueError("unterminated long string")
            out.append('""' + "\n" * src.count("\n", i, end))
            i = end + len(close)
            continue
        if ch in "\"'`":
            quote = ch
            j = i + 1
            while j < n and src[j] != quote:
                if src[j] == "\\":
                    j += 1
                elif src[j] == "\n":
                    raise ValueError("unterminated string on line %d" % (src.count("\n", 0, i) + 1))
                j += 1
            if j >= n:
                raise ValueError("unterminated string")
            out.append('""')
            i = j + 1
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def check_luau(src, is_module):
    """Returns a list of error strings (empty = OK)."""
    errors = []
    try:
        code = strip_luau(src)
    except ValueError as exc:
        return [str(exc)]
    pairs = {")": "(", "]": "[", "}": "{"}
    stack = []
    for lineno, line in enumerate(code.split("\n"), 1):
        for ch in line:
            if ch in "([{":
                stack.append((ch, lineno))
            elif ch in ")]}":
                if not stack or stack[-1][0] != pairs[ch]:
                    errors.append("unbalanced '%s' on line %d" % (ch, lineno))
                    return errors
                stack.pop()
    if stack:
        errors.append("unclosed '%s' from line %d" % stack[-1])
        return errors

    tokens = []
    for lineno, line in enumerate(code.split("\n"), 1):
        for m in re.finditer(r"[A-Za-z_][A-Za-z0-9_]*|\"\"|\d[\w.]*|\.\.\.|==|~=|<=|>=|!=|//=|\.\.=|[-+*/%^]=|[=(){}\[\],]", line):
            tokens.append((m.group(0), lineno, m.start(), line))
    blocks = []
    prev = None
    for tok, lineno, col, line in tokens:
        before = line[:col].rstrip()
        if before.endswith(".") or before.endswith(":"):
            prev = tok
            continue  # field access like t.end is not a keyword
        if tok == "!=":
            errors.append("'!=' is not Luau (use '~=') on line %d" % lineno)
        elif tok in ("function", "do", "repeat"):
            blocks.append((tok, lineno))
        elif tok == "if":
            if prev in ("=", "(", ",", "{", "[", "return", "and", "or"):
                pass  # if-expression, no 'end'
            else:
                blocks.append((tok, lineno))
        elif tok == "end":
            if not blocks or blocks[-1][0] == "repeat":
                errors.append("unexpected 'end' on line %d" % lineno)
                return errors
            blocks.pop()
        elif tok == "until":
            if not blocks or blocks[-1][0] != "repeat":
                errors.append("unexpected 'until' on line %d" % lineno)
                return errors
            blocks.pop()
        prev = tok
    if blocks:
        errors.append("'%s' on line %d is never closed" % blocks[-1])
    if is_module:
        if not any(l.startswith("return") for l in code.split("\n")):
            errors.append("ModuleScript must have a top-level (unindented) 'return'")
    return errors

