# -*- coding: utf-8 -*-
"""WAR STATE country registry source: 195 sovereign states (193 UN members + Holy See + State of Palestine).
(Id = ISO 3166-1 alpha-2, DisplayNameEN, DisplayNameRU, Continent). Used by build_war_state.py --write-registry."""

CONTINENTS = ["Europe", "Asia", "Africa", "North America", "South America", "Oceania"]

EXPECTED_CONTINENT_COUNTS = {
    "Europe": 45,
    "Asia": 47,
    "Africa": 54,
    "North America": 23,
    "South America": 12,
    "Oceania": 14,
}

# Real flag assets: ONLY add verified Roblox asset ids here ("rbxassetid://<id>"). Never invent ids.
REAL_FLAG_ASSETS = {}

COUNTRIES = [
    # Europe (45)
    ("AL", "Albania", "Албания", "Europe"),
    ("AD", "Andorra", "Андорра", "Europe"),
    ("AT", "Austria", "Австрия", "Europe"),
    ("BY", "Belarus", "Беларусь", "Europe"),
    ("BE", "Belgium", "Бельгия", "Europe"),
    ("BA", "Bosnia and Herzegovina", "Босния и Герцеговина", "Europe"),
    ("BG", "Bulgaria", "Болгария", "Europe"),
    ("HR", "Croatia", "Хорватия", "Europe"),
    ("CY", "Cyprus", "Кипр", "Europe"),
    ("CZ", "Czechia", "Чехия", "Europe"),
    ("DK", "Denmark", "Дания", "Europe"),
    ("EE", "Estonia", "Эстония", "Europe"),
    ("FI", "Finland", "Финляндия", "Europe"),
    ("FR", "France", "Франция", "Europe"),
    ("DE", "Germany", "Германия", "Europe"),
    ("GR", "Greece", "Греция", "Europe"),
    ("HU", "Hungary", "Венгрия", "Europe"),
    ("IS", "Iceland", "Исландия", "Europe"),
    ("IE", "Ireland", "Ирландия", "Europe"),
    ("IT", "Italy", "Италия", "Europe"),
    ("LV", "Latvia", "Латвия", "Europe"),
    ("LI", "Liechtenstein", "Лихтенштейн", "Europe"),
    ("LT", "Lithuania", "Литва", "Europe"),
    ("LU", "Luxembourg", "Люксембург", "Europe"),
    ("MT", "Malta", "Мальта", "Europe"),
    ("MD", "Moldova", "Молдова", "Europe"),
    ("MC", "Monaco", "Монако", "Europe"),
    ("ME", "Montenegro", "Черногория", "Europe"),
    ("NL", "Netherlands", "Нидерланды", "Europe"),
    ("MK", "North Macedonia", "Северная Македония", "Europe"),
    ("NO", "Norway", "Норвегия", "Europe"),
    ("PL", "Poland", "Польша", "Europe"),
    ("PT", "Portugal", "Португалия", "Europe"),
    ("RO", "Romania", "Румыния", "Europe"),
    ("RU", "Russia", "Россия", "Europe"),
    ("SM", "San Marino", "Сан-Марино", "Europe"),
    ("RS", "Serbia", "Сербия", "Europe"),
    ("SK", "Slovakia", "Словакия", "Europe"),
    ("SI", "Slovenia", "Словения", "Europe"),
    ("ES", "Spain", "Испания", "Europe"),
    ("SE", "Sweden", "Швеция", "Europe"),
    ("CH", "Switzerland", "Швейцария", "Europe"),
    ("UA", "Ukraine", "Украина", "Europe"),
    ("GB", "United Kingdom", "Великобритания", "Europe"),
    ("VA", "Holy See (Vatican City)", "Ватикан", "Europe"),
    # Asia (47)
    ("AF", "Afghanistan", "Афганистан", "Asia"),
    ("AM", "Armenia", "Армения", "Asia"),
    ("AZ", "Azerbaijan", "Азербайджан", "Asia"),
    ("BH", "Bahrain", "Бахрейн", "Asia"),
    ("BD", "Bangladesh", "Бангладеш", "Asia"),
    ("BT", "Bhutan", "Бутан", "Asia"),
    ("BN", "Brunei", "Бруней", "Asia"),
    ("KH", "Cambodia", "Камбоджа", "Asia"),
    ("CN", "China", "Китай", "Asia"),
    ("GE", "Georgia", "Грузия", "Asia"),
    ("IN", "India", "Индия", "Asia"),
    ("ID", "Indonesia", "Индонезия", "Asia"),
    ("IR", "Iran", "Иран", "Asia"),
    ("IQ", "Iraq", "Ирак", "Asia"),
    ("IL", "Israel", "Израиль", "Asia"),
    ("JP", "Japan", "Япония", "Asia"),
    ("JO", "Jordan", "Иордания", "Asia"),
    ("KZ", "Kazakhstan", "Казахстан", "Asia"),
    ("KW", "Kuwait", "Кувейт", "Asia"),
    ("KG", "Kyrgyzstan", "Киргизия", "Asia"),
    ("LA", "Laos", "Лаос", "Asia"),
    ("LB", "Lebanon", "Ливан", "Asia"),
    ("MY", "Malaysia", "Малайзия", "Asia"),
    ("MV", "Maldives", "Мальдивы", "Asia"),
    ("MN", "Mongolia", "Монголия", "Asia"),
    ("MM", "Myanmar", "Мьянма", "Asia"),
    ("NP", "Nepal", "Непал", "Asia"),
    ("KP", "North Korea", "КНДР", "Asia"),
    ("OM", "Oman", "Оман", "Asia"),
    ("PK", "Pakistan", "Пакистан", "Asia"),
    ("PS", "State of Palestine", "Государство Палестина", "Asia"),
    ("PH", "Philippines", "Филиппины", "Asia"),
    ("QA", "Qatar", "Катар", "Asia"),
    ("SA", "Saudi Arabia", "Саудовская Аравия", "Asia"),
    ("SG", "Singapore", "Сингапур", "Asia"),
    ("KR", "South Korea", "Республика Корея", "Asia"),
    ("LK", "Sri Lanka", "Шри-Ланка", "Asia"),
    ("SY", "Syria", "Сирия", "Asia"),
    ("TJ", "Tajikistan", "Таджикистан", "Asia"),
    ("TH", "Thailand", "Таиланд", "Asia"),
    ("TL", "Timor-Leste", "Восточный Тимор", "Asia"),
    ("TR", "Turkey", "Турция", "Asia"),
    ("TM", "Turkmenistan", "Туркменистан", "Asia"),
    ("AE", "United Arab Emirates", "ОАЭ", "Asia"),
    ("UZ", "Uzbekistan", "Узбекистан", "Asia"),
    ("VN", "Vietnam", "Вьетнам", "Asia"),
    ("YE", "Yemen", "Йемен", "Asia"),
    # Africa (54)
    ("DZ", "Algeria", "Алжир", "Africa"),
    ("AO", "Angola", "Ангола", "Africa"),
    ("BJ", "Benin", "Бенин", "Africa"),
    ("BW", "Botswana", "Ботсвана", "Africa"),
    ("BF", "Burkina Faso", "Буркина-Фасо", "Africa"),
    ("BI", "Burundi", "Бурунди", "Africa"),
    ("CV", "Cabo Verde", "Кабо-Верде", "Africa"),
    ("CM", "Cameroon", "Камерун", "Africa"),
    ("CF", "Central African Republic", "Центральноафриканская Республика", "Africa"),
    ("TD", "Chad", "Чад", "Africa"),
    ("KM", "Comoros", "Коморы", "Africa"),
    ("CG", "Republic of the Congo", "Республика Конго", "Africa"),
    ("CD", "DR Congo", "ДР Конго", "Africa"),
    ("CI", "Cote d'Ivoire", "Кот-д'Ивуар", "Africa"),
    ("DJ", "Djibouti", "Джибути", "Africa"),
    ("EG", "Egypt", "Египет", "Africa"),
    ("GQ", "Equatorial Guinea", "Экваториальная Гвинея", "Africa"),
    ("ER", "Eritrea", "Эритрея", "Africa"),
    ("SZ", "Eswatini", "Эсватини", "Africa"),
    ("ET", "Ethiopia", "Эфиопия", "Africa"),
    ("GA", "Gabon", "Габон", "Africa"),
    ("GM", "Gambia", "Гамбия", "Africa"),
    ("GH", "Ghana", "Гана", "Africa"),
    ("GN", "Guinea", "Гвинея", "Africa"),
    ("GW", "Guinea-Bissau", "Гвинея-Бисау", "Africa"),
    ("KE", "Kenya", "Кения", "Africa"),
    ("LS", "Lesotho", "Лесото", "Africa"),
    ("LR", "Liberia", "Либерия", "Africa"),
    ("LY", "Libya", "Ливия", "Africa"),
    ("MG", "Madagascar", "Мадагаскар", "Africa"),
    ("MW", "Malawi", "Малави", "Africa"),
    ("ML", "Mali", "Мали", "Africa"),
    ("MR", "Mauritania", "Мавритания", "Africa"),
    ("MU", "Mauritius", "Маврикий", "Africa"),
    ("MA", "Morocco", "Марокко", "Africa"),
    ("MZ", "Mozambique", "Мозамбик", "Africa"),
    ("NA", "Namibia", "Намибия", "Africa"),
    ("NE", "Niger", "Нигер", "Africa"),
    ("NG", "Nigeria", "Нигерия", "Africa"),
    ("RW", "Rwanda", "Руанда", "Africa"),
    ("ST", "Sao Tome and Principe", "Сан-Томе и Принсипи", "Africa"),
    ("SN", "Senegal", "Сенегал", "Africa"),
    ("SC", "Seychelles", "Сейшельские Острова", "Africa"),
    ("SL", "Sierra Leone", "Сьерра-Леоне", "Africa"),
    ("SO", "Somalia", "Сомали", "Africa"),
    ("ZA", "South Africa", "ЮАР", "Africa"),
    ("SS", "South Sudan", "Южный Судан", "Africa"),
    ("SD", "Sudan", "Судан", "Africa"),
    ("TZ", "Tanzania", "Танзания", "Africa"),
    ("TG", "Togo", "Того", "Africa"),
    ("TN", "Tunisia", "Тунис", "Africa"),
    ("UG", "Uganda", "Уганда", "Africa"),
    ("ZM", "Zambia", "Замбия", "Africa"),
    ("ZW", "Zimbabwe", "Зимбабве", "Africa"),
    # North America (23)
    ("AG", "Antigua and Barbuda", "Антигуа и Барбуда", "North America"),
    ("BS", "Bahamas", "Багамские Острова", "North America"),
    ("BB", "Barbados", "Барбадос", "North America"),
    ("BZ", "Belize", "Белиз", "North America"),
    ("CA", "Canada", "Канада", "North America"),
    ("CR", "Costa Rica", "Коста-Рика", "North America"),
    ("CU", "Cuba", "Куба", "North America"),
    ("DM", "Dominica", "Доминика", "North America"),
    ("DO", "Dominican Republic", "Доминиканская Республика", "North America"),
    ("SV", "El Salvador", "Сальвадор", "North America"),
    ("GD", "Grenada", "Гренада", "North America"),
    ("GT", "Guatemala", "Гватемала", "North America"),
    ("HT", "Haiti", "Гаити", "North America"),
    ("HN", "Honduras", "Гондурас", "North America"),
    ("JM", "Jamaica", "Ямайка", "North America"),
    ("MX", "Mexico", "Мексика", "North America"),
    ("NI", "Nicaragua", "Никарагуа", "North America"),
    ("PA", "Panama", "Панама", "North America"),
    ("KN", "Saint Kitts and Nevis", "Сент-Китс и Невис", "North America"),
    ("LC", "Saint Lucia", "Сент-Люсия", "North America"),
    ("VC", "Saint Vincent and the Grenadines", "Сент-Винсент и Гренадины", "North America"),
    ("TT", "Trinidad and Tobago", "Тринидад и Тобаго", "North America"),
    ("US", "United States", "США", "North America"),
    # South America (12)
    ("AR", "Argentina", "Аргентина", "South America"),
    ("BO", "Bolivia", "Боливия", "South America"),
    ("BR", "Brazil", "Бразилия", "South America"),
    ("CL", "Chile", "Чили", "South America"),
    ("CO", "Colombia", "Колумбия", "South America"),
    ("EC", "Ecuador", "Эквадор", "South America"),
    ("GY", "Guyana", "Гайана", "South America"),
    ("PY", "Paraguay", "Парагвай", "South America"),
    ("PE", "Peru", "Перу", "South America"),
    ("SR", "Suriname", "Суринам", "South America"),
    ("UY", "Uruguay", "Уругвай", "South America"),
    ("VE", "Venezuela", "Венесуэла", "South America"),
    # Oceania (14)
    ("AU", "Australia", "Австралия", "Oceania"),
    ("FJ", "Fiji", "Фиджи", "Oceania"),
    ("KI", "Kiribati", "Кирибати", "Oceania"),
    ("MH", "Marshall Islands", "Маршалловы Острова", "Oceania"),
    ("FM", "Micronesia", "Микронезия", "Oceania"),
    ("NR", "Nauru", "Науру", "Oceania"),
    ("NZ", "New Zealand", "Новая Зеландия", "Oceania"),
    ("PW", "Palau", "Палау", "Oceania"),
    ("PG", "Papua New Guinea", "Папуа - Новая Гвинея", "Oceania"),
    ("WS", "Samoa", "Самоа", "Oceania"),
    ("SB", "Solomon Islands", "Соломоновы Острова", "Oceania"),
    ("TO", "Tonga", "Тонга", "Oceania"),
    ("TV", "Tuvalu", "Тувалу", "Oceania"),
    ("VU", "Vanuatu", "Вануату", "Oceania"),
]


def emoji_flag(iso2):
    return "".join(chr(0x1F1E6 + ord(ch) - ord("A")) for ch in iso2.upper())


def country_registry():
    countries = []
    for iso, en, ru, continent in COUNTRIES:
        countries.append(
            {
                "Id": iso,
                "Iso2": iso,
                "DisplayNameEN": en,
                "DisplayNameRU": ru,
                "Continent": continent,
                "FlagAsset": REAL_FLAG_ASSETS.get(iso, ""),
                "EmojiFallback": emoji_flag(iso),
            }
        )
    return {
        "RegistryVersion": 1,
        "Continents": CONTINENTS,
        "ExpectedContinentCounts": EXPECTED_CONTINENT_COUNTS,
        "Countries": countries,
    }
